name: hood
channels:
  - conda-forge
  - defaults
  - nvidia
  - pytorch
  - bottler
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - contourpy=1.0.5
  - cryptography=39.0.1
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - debugpy=1.5.1
  - decorator=5.1.1
  - einops=0.6.1
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.2.10
  - ffmpeg=4.3
  - filelock=3.9.0
  - fontconfig=2.14.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fvcore=0.1.5.post20221221
  - giflib=5.2.1
  - glib=2.69.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - icu=58.2
  - idna=3.4
  - intel-openmp=2023.1.0
  - iopath=0.1.9
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=7.3.4
  - jupyter_core=5.3.0
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=10.0.1
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.6.1.9
  - libcurand=10.3.2.106
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblapack=3.9.0
  - libllvm10=10.0.1
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.6
  - mkl_random=1.2.2
  - mpc=1.1.0
  - mpfr=4.0.2
  - munch=3.0.0
  - munkres=1.1.4
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - networkx=2.8.4
  - nspr=4.35
  - nss=3.89.1
  - numexpr=2.8.4
  - numpy-base=1.23.5
  # - nvidiacub=1.10.0
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openssl=1.1.1t
  - packaging=23.1
  - pandas=1.5.3
  - parso=0.8.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.4.0
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - portalocker=2.7.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.15.1
  - pyopenssl=23.0.0
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pysocks=1.7.1
  - python=3.10.9
  - python-dateutil=2.8.2
  - python_abi=3.10
  # - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - pytz=2023.3
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.29.0
  - scikit-learn=1.2.2
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tabulate=0.9.0
  - tbb=2021.8.0
  - termcolor=2.3.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.1
  - tqdm=4.65.0
  - traitlets=5.7.1
  - tzdata=2023c
  - urllib3=1.26.15
  - wcwidth=0.2.5
  - xz=5.4.2
  - yacs=0.1.8
  - yaml=0.2.5
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - aitviewer==1.13.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - chumpy==0.70
      - cmake==4.1.0
      - frozenlist==1.7.0
      - fsspec==2025.9.0
      - glcontext==2.3.7
      - graphviz==0.8.4
      - huepy==1.2.1
      - imageio==2.31.0
      - imgui==2.0.0
      - moderngl==5.8.2
      - moderngl-window==2.4.4
      - mpmath==1.2.1
      - multidict==6.6.4
      - multipledispatch==0.6.0
      - mxnet-mkl==1.6.0
      - ninja==1.13.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - opencv-contrib-python-headless==4.7.0.72
      - pip==25.2
      - propcache==0.3.2
      - pybind11==3.0.1
      - pybind11-global==3.0.1
      - pyglet==2.0.7
      - pyqt5==5.15.9
      - pyqt5-qt5==5.15.2
      - pyqt5-sip==12.11.0
      - pyrr==0.10.3
      - pywavelets==1.4.1
      - roma==1.3.2
      - scikit-image==0.19.3
      - scikit-video==1.1.11
      - scipy==1.11.4
      - setuptools==80.9.0
      - smplx==0.1.28
      - sympy==1.13.3
      - tifffile==2023.4.12
      - --extra-index-url https://download.pytorch.org/whl/cu128
      - torch==2.8.0
      - torchaudio==2.8.0
      - torchvision==0.23.0
      - torch-geometric==2.3.1
      - trimesh==3.21.7
      - triton==3.4.0
      - typing-extensions==4.15.0
      - websockets==11.0.3
      - wheel==0.45.1
      - yarl==1.20.1
